version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fullstack

  migrator:
    image: migrate/migrate
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://$DB_USER:$DB_PASSWORD@postgres:$DB_PORT/$DB_NAME?sslmode=disable",
        "up",
      ]
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    networks:
      - fullstack

  app:
    container_name: app
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    networks:
      - fullstack

volumes:
  postgres-data:

networks:
  fullstack:
    driver: bridge
